language: java
sudo: false
jdk: oraclejdk8
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_202c1d785c11_key -iv $encrypted_202c1d785c11_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/89cf359368eec1daf567
    on_success: change
    on_failure: always
    on_start: never
